name: my_app
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.5.4
  firebase_analytics: ^10.10.7
  firebase_messaging: ^14.9.1
  firebase_remote_config: ^4.4.4

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
